import 'dotenv/config'

export const {
  PORT = 3000,
  SECRET_JWT_KEY,
  STORAGE_BUCKET,
  FIREBASE_PROJECT_ID,
  FIREBASE_PRIVATE_KEY_ID,
  FIREBASE_PRIVATE_KEY,
  FIREBASE_CLIENT_EMAIL,
  FIREBASE_CLIENT_ID,
  FIREBASE_CLIENT_CERT_URL
} = process.env

export const SALT_ROUND = 10